CREATE DATABASE IF NOT EXISTS  `cloudsystem`;

-- USERS TABLE
CREATE TABLE `users` ( `id` INT NOT NULL AUTO_INCREMENT , 
`fullname` VARCHAR(100) NOT NULL , 
`regNo` VARCHAR(100) NOT NULL , 
`password` VARCHAR(200) NOT NULL , 
PRIMARY KEY (`id`)) ENGINE = InnoDB;

-- CLOUD STORAGE TABLE (FILES)
CREATE TABLE `files` ( `id` INT NOT NULL AUTO_INCREMENT , 
`userid` INT NOT NULL , 
`file_name` VARCHAR(100) NOT NULL , 
`file_type` VARCHAR(50) NOT NULL , 
PRIMARY KEY (`id`)) ENGINE = InnoDB;
